services:
  - type: web
    name: gym-backend
    rootDir: backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build && npm run prisma:migrate
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      # Set the following in Render dashboard with real values:
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
